name: Bytebase rollout SQL migrations

on:
  push:
    branches:
      - main
    paths:
      - "*/overlays/**/migrations/*.up.sql"
      - ".github/workflows/sql-rollout.yml" # to allow workflow updates

jobs:
  rollout-to-qa:
    uses: naing2htun/actions/.github/workflows/sql-rollout.yml@main
    with:
      bytebase-url: ${{ vars.BYTEBASE_URL_NONPROD }}
      bytebase-service-account: ${{ vars.BYTEBASE_SERVICE_ACCOUNT_NONPROD }}
      project: "projects/latitude-demo"
      target-stage: "environments/qa"
      full-repo: "naing2htun/latitude-demo"
    secrets:
      bytebase-service-account-secret: ${{ secrets.BYTEBASE_SERVICE_ACCOUNT_SECRET_NONPROD }}
      access-token: ${{ secrets.GITHUB_TOKEN }}