name: Promote to Production

on:
  push:
    branches:
      - main
    paths:
      - "*/overlays/stg/migrations/*.up.sql"

jobs:
  promote:
    uses: naing2htun/actions/.github/workflows/sql-promotion.yml@main
    with:
      stage-environment: "stg"
    secrets:
      service-repo-token: ${{ secrets.SERVICE_REPO_TOKEN }}